//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("cat ver:0.9.31026.7")]
[assembly: System.Reflection.AssemblyDescription("cat")]
[assembly: System.Reflection.AssemblyProduct("cat")]
[assembly: System.Reflection.AssemblyCopyright("Copyright (C) 2003-2013 Kody Brown.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.Guid("80C5C00E-280C-49C1-B2FC-4C6B1562CEE6")]
[assembly: System.Reflection.AssemblyVersion("0.9.31026.7")]
[assembly: System.Reflection.AssemblyFileVersion("0.9.31026.7")]


