//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("cat ver:0.9.30929.4")]
[assembly: AssemblyDescription("cat")]
[assembly: AssemblyProduct("cat")]
[assembly: AssemblyCopyright("Copyright (C) 2003-2013 Kody Brown.")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("80C5C00E-280C-49C1-B2FC-4C6B1562CEE6")]
[assembly: AssemblyVersion("0.9.30929.4")]
[assembly: AssemblyFileVersion("0.9.30929.4")]


